# Generated by Django 4.2 on 2023-06-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_alter_product_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=15)),
                ("addressline1", models.CharField(max_length=100)),
                ("addressline2", models.CharField(max_length=100)),
                ("addressline3", models.CharField(max_length=100)),
                ("pin", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("pic", models.ImageField(upload_to="buyers")),
            ],
        ),
        migrations.AddField(
            model_name="brand",
            name="pic",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="brands"
            ),
        ),
    ]
