# Generated by Django 4.2 on 2023-06-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_buyer_brand_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="username",
            field=models.CharField(default="", max_length=30),
        ),
    ]
